{{ if .Values.mongodb.persistence.createNew }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.mongodb.persistence.existingClaim}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  {{- with .Values.mongodb.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
{{ end }}
