name: Container CI

on:
  push:
    branches:
    - master
  release:
    types: [published]

jobs:
  build-and-push-image:
    timeout-minutes: 60

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          tags: gcr.io/diamond-pubreg/diffcalc/api:latest
          containerfiles: |
            ./Dockerfile
      
      - name: Push to diamond pubreg 
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.build-image.outputs.tags }}
          registry: gcr.io