name: Docs CI

on:
  push:
    branches:
      # Add more branches here to publish docs from other branches
      - master
      - main
    tags:
      - "*"
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Avoid git conflicts when tag and branch pushed at same time
        if: startsWith(github.ref, 'refs/tags')
        run: sleep 60

      - name: Install Packages
        # Can delete this if you don't use graphviz in your docs
        run: sudo apt-get install graphviz

      - name: Build docs
        uses: dls-controls/pipenv-run-action@v1
        with:
          pipenv-run: docs
