name: Helm CI

on:
  push:
    tags:
      - '*'

env:
  GCR_IMAGE: ghcr.io/rayemelyanova/diffcalc-api
  HELM_VERSION: 0.1.0

jobs:
  build:
    name: publish gcr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout repo 
        uses: actions/checkout@v2
      
      - name: install helm
        uses: Azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: login to acr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag


      - name: package chart and push it
        run: |
          helm dependencies update helm/diffcalc-api
          helm package helm/diffcalc-api --version ${GITHUB_REF##*/} -d /tmp/
          helm push /tmp/diffcalc-api-${GITHUB_REF##*/}.tgz oci://ghcr.io/rayemelyanova/charts