name: openapi

on: [push]

jobs:
  install-and-run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Setup repo and test
        uses: dls-controls/pipenv-run-action@v1
        with:
          python-version: 3.8
          pipenv-install: --dev
          pipenv-run: python src/diffcalc_API/openapi.py

    # - name: Install dependecies
    #   uses: VaultVulp/action-pipenv@v2.0.1
    #   with:
    #     command: install -d # Install all dependencies, including development ones
    
    # - name: Test
    #   uses: VaultVulp/action-pipenv@v2.0.1
    #   with:
    #     command: run python src/diffcalc_API/openapi.py

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: openapi.json
        path: openapi/
