name: Openapi CI

on:
  push:
    tags:
      - '*'

jobs:
  install-and-run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      if: ${{ !matrix.deploy }}
      run: |
        python -m pip install --upgrade pip
        pip install .[dev] -r requirements.txt

    - name: Make openapi.json
      run: |
        python src/diffcalc_API/openapi.py

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: openapi.json
        path: openapi.json

    - name: Delete json after upload
      run: rm openapi.json

  release:
    needs: [install-and-run-script]
    runs-on: ubuntu-latest
    # upload to PyPI and make a release on every tag
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: openapi.json
          path: openapi/

      - name: Github Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # v0.1.14
        with:
          files: openapi/openapi.json
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
